---
title: "LDA training on random subsets of different sizes"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```

Experiment on CIFAR10 dataset.
This experiment trained WeightedLDAEnsemble on various subsets of different sizes of data on which nn were trained. Subsets of the same size are disjoint. Three different coupling methods were used: method one and two from Wu, Lin and Weng and Bayes Covariant method.

```{r}
acc_ens_subsets <- read.csv("../train_data/1/exp_subsets_sizes_train_outputs/accuracies.csv", stringsAsFactors=TRUE)
acc_nets <- read.csv("../train_data/1/exp_subsets_sizes_train_outputs/net_accuracies.csv", stringsAsFactors=TRUE)
```

```{r}
scatter <- ggplot() + geom_point(data=acc_ens_subsets, mapping=aes(x=train_size, y=accuracy, fill=method), alpha=0.7, pch=21) + geom_hline(data=acc_nets, mapping=aes(yintercept=accuracy, color=network), size=1)
scatter
```
```{r}
scatter2 <- ggplot() + geom_point(data=acc_ens_subsets, mapping=aes(x=train_size, y=accuracy, color=method), alpha=0.7)
scatter2
```


```{r}

box_acc <- ggplot() + geom_boxplot(data=acc_ens_subsets, mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size)
box_acc
```

```{r}
acc_ens_subsets %>% filter(0 < train_size & train_size < 200) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size, nrow = 1)
```
```{r}
acc_ens_subsets %>% filter(100 < train_size & train_size < 500) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size, nrow = 1)
```

```{r}
acc_ens_subsets %>% filter(200 < train_size & train_size < 1000) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size, nrow = 1)
```
```{r}
acc_ens_subsets %>% filter(500 < train_size & train_size < 3000) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size, nrow = 1)
```

```{r}
acc_ens_subsets %>% filter(1000 < train_size & train_size < 5000) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = accuracy, color=method)) + facet_wrap(~train_size, nrow = 1)
```

```{r}

box_nll <- ggplot() + geom_boxplot(data=acc_ens_subsets, mapping=aes(x=method, y = nll, color=method)) + facet_wrap(~train_size)
box_nll
```
Nll doesn't seem to be doing much with changing LDA train size.

```{r}
acc_ens_subsets %>% filter(200 < train_size & train_size < 1000) %>% ggplot() + geom_boxplot(mapping=aes(x=method, y = nll, color=method)) + facet_wrap(~train_size, nrow = 1)
```

