---
title: "WeightedLinearEnsemble evaluation new"
output:
  pdf_document: default
  html_notebook: default
header-includes:
   - \usepackage{longtable}
bibliography: references.bib
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(comprehenr)
library(stringr)
library(ungeviz)
library(relayer)
library(patchwork)
library(xtable)
```


```{r}
my_plot_hook <- function(x, options)
  paste("\n", knitr::hook_plot_tex(x, options), "\n")
knitr::knit_hooks$set(plot = my_plot_hook)

base_dir <- "D:/skola/1/weighted_ensembles/tests/test_cifar_2021/data/data_tv_5000_c100/0/newnew"
net_df <- read.csv(file.path(base_dir, "net_metrics.csv"))
ens_df_cal <- read.csv(file.path(base_dir, "ens_cal_metrics.csv"))
ens_df_pwc <- read.csv(file.path(base_dir, "ens_pwc_metrics.csv"))

net_long <- pivot_longer(net_df,
  cols = c("accuracy", "nll", "ece"),
  names_to = "metric", values_to = "value"
)
ens_cal_long <- pivot_longer(ens_df_cal,
  cols = c("accuracy", "nll", "ece"),
  names_to = "metric", values_to = "value"
)
ens_pwc_long <- pivot_longer(ens_df_pwc,
  cols = c("accuracy", "nll", "ece"),
  names_to = "metric", values_to = "value"
)

networks <- net_df$network

comb_stats_df <- data.frame(matrix(
  ncol = 14, nrow = 0,
  dimnames = list(NULL, c(
    "combination_size", "combination_id",
    "acc_min", "acc_max", "acc_avg", "acc_var",
    "nll_min", "nll_max", "nll_avg", "nll_var",
    "ece_min", "ece_max", "ece_avg", "ece_var"
  ))
))

for (sss in unique(ens_df_cal$combination_size))
{
  for (ssi in unique(ens_df_cal %>%
    filter(combination_size == sss) %>%
    pull(combination_id)))
  {
    cur_nets_vec <- to_vec(
      for (net in networks) {
        if (str_replace_all(net, "-", ".") %in% colnames(ens_cal_long) &&
          (ens_cal_long %>%
            filter(combination_size == sss & combination_id == ssi) %>%
            pull(str_replace_all(net, "-", ".")))[1] == "True") {
          net
        }
      }
    )
    cur_nets <- net_df %>% filter(network %in% cur_nets_vec)
    comb_stats_df[nrow(comb_stats_df) + 1, ] <- c(
      sss, ssi,
      min(cur_nets$accuracy), max(cur_nets$accuracy), mean(cur_nets$accuracy), var(cur_nets$accuracy),
      min(cur_nets$nll), max(cur_nets$nll), mean(cur_nets$nll), var(cur_nets$nll),
      min(cur_nets$ece), max(cur_nets$ece), mean(cur_nets$ece), var(cur_nets$ece)
    )
  }
}

ens_df_cal <- merge(ens_df_cal, comb_stats_df)
ens_df_cal$acc_imp_avg <- ens_df_cal$accuracy - ens_df_cal$acc_avg
ens_df_cal$acc_imp_max <- ens_df_cal$accuracy - ens_df_cal$acc_max

ens_df_pwc <- merge(ens_df_pwc, comb_stats_df)
ens_df_pwc$acc_imp_avg <- ens_df_pwc$accuracy - ens_df_pwc$acc_avg
ens_df_pwc$acc_imp_max <- ens_df_pwc$accuracy - ens_df_pwc$acc_max
```

```{r}
nets_plot <- ggplot(data = net_long) +
  geom_col(mapping = aes(x = network, y = value)) +
  facet_grid(rows = vars(metric), scales = "free") +
  theme(axis.text.x = element_text(angle = 90)) +
  ggtitle("Metrics of networks")

nets_plot
```

```{r setup, warning=FALSE, fig.height=9, fig.fig.width=8}
ens_pwc_plt_df <- ens_df_pwc %>% filter(combining_method != "lda")
ens_cal_plt_df <- ens_df_cal

comb_methods <- c(
    "average", "prob_average",
    "cal_average", "cal_prob_average",
    "logreg", "logreg_sweep_C",
    "logreg_no_interc", "logreg_no_interc_sweep_C",
    "grad_m1", "grad_m2", "grad_bc"
  )
comb_methods <- c(sapply(X=comb_methods, FUN={function(cm) c(cm, paste(cm, "uncert", sep="."))}))

ens_pwc_plt_df$combining_method <- factor(ens_pwc_plt_df$combining_method,
  levels = comb_methods)

for (sss in unique(ens_cal_plt_df$combination_size))
{
  for (ssi in unique(ens_cal_plt_df %>%
    filter(combination_size == sss) %>%
    pull(combination_id)))
  {
    cur_ens_cal <- ens_cal_plt_df %>% filter(combination_size == sss &
      combination_id == ssi)
    cur_ens_pwc <- ens_pwc_plt_df %>% filter(combination_size == sss &
      combination_id == ssi)
    cur_nets_vec <- to_vec(
      for (net in networks) {
        if (str_replace_all(net, "-", ".") %in% colnames(cur_ens_cal) &&
          cur_ens_cal[[str_replace_all(net, "-", ".")]][1] == "True") {
          net
        }
      }
    )
    cur_nets <- net_df %>% filter(network %in% cur_nets_vec)

    acc_plot <- ggplot() +
      (
        geom_hline(
          data = cur_nets,
          mapping = aes(yintercept = accuracy, colour1 = network),
          linetype = "dashed"
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour1"))
      ) +
      geom_hline(
        data = cur_ens_cal,
        mapping = aes(yintercept = accuracy, color = "cal ensemble")
      ) +
      (
        geom_hpline(
          data = cur_ens_pwc,
          mapping = aes(
            x = combining_method, y = accuracy,
            colour2 = coupling_method
          ),
          size = 0.8, width = 0.11,
          position = position_dodge(width = 0.65)
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour2"))
      ) +
      scale_colour_brewer(
        aesthetics = "colour1", palette = 1,
        name = "network", type = "qual"
      ) +
      scale_colour_brewer(
        aesthetics = "colour2", palette = 2,
        name = "coupling method", type = "qual"
      ) +
      scale_color_manual(values = c("black"), name = "averaging ensemble") +
      theme(
        axis.text.x = element_blank(),
        axis.title.x = element_blank()
      )

    y_limits <- layer_scales(acc_plot)$y$get_limits()
    x_limits <- layer_scales(acc_plot)$x$get_limits()
    all_y_lim <- c(y_limits[1], cur_ens_cal$all_cor)

    acc_plot <- acc_plot +
      geom_rect(
        data = cur_ens_cal,
        mapping = aes(
          xmin = 0.5,
          xmax = length(x_limits) + 0.5,
          ymin = max(all_cor, y_limits[1]), ymax = all_cor + err_incons
        ),
        fill = "orange",
        alpha = 0.3, color = NA
      )

    if (all_y_lim[1] < all_y_lim[2]) {
      acc_plot <- acc_plot +
        geom_rect(
          data = cur_ens_cal,
          mapping = aes(
            xmin = 0.5,
            xmax = length(x_limits) + 0.5,
            ymin = all_y_lim[1], ymax = all_y_lim[2]
          ), fill = "green",
          alpha = 0.3, color = NA
        )
    }

    nll_plot <- ggplot() +
      (
        geom_hline(
          data = cur_nets,
          mapping = aes(yintercept = nll, colour1 = network),
          linetype = "dashed"
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour1"))
      ) +
      geom_hline(
        data = cur_ens_cal,
        mapping = aes(yintercept = nll, color = "cal ensemble")
      ) +
      (
        geom_hpline(
          data = cur_ens_pwc,
          mapping = aes(
            x = combining_method, y = nll,
            colour2 = coupling_method
          ),
          size = 0.8, width = 0.11,
          position = position_dodge(width = 0.65)
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour2"))
      ) +
      scale_colour_brewer(
        aesthetics = "colour1", palette = 1,
        name = "network", type = "qual"
      ) +
      scale_colour_brewer(
        aesthetics = "colour2", palette = 2,
        name = "coupling method", type = "qual"
      ) +
      scale_color_manual(values = c("black"), name = "averaging ensemble") +
      scale_y_reverse() +
      theme(
        axis.text.x = element_blank(),
        axis.title.x = element_blank()
      )

    ece_plot <- ggplot() +
      (
        geom_hline(
          data = cur_nets,
          mapping = aes(yintercept = ece, colour1 = network),
          linetype = "dashed"
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour1"))
      ) +
      geom_hline(
        data = cur_ens_cal,
        mapping = aes(yintercept = ece, color = "cal ensemble")
      ) +
      (
        geom_hpline(
          data = cur_ens_pwc,
          mapping = aes(
            x = combining_method, y = ece,
            colour2 = coupling_method
          ),
          size = 0.8, width = 0.11,
          position = position_dodge(width = 0.65)
        ) %>%
          rename_geom_aes(new_aes = c("colour" = "colour2"))
      ) +
      scale_colour_brewer(
        aesthetics = "colour1", palette = 1,
        name = "network", type = "qual"
      ) +
      scale_colour_brewer(
        aesthetics = "colour2", palette = 2,
        name = "coupling method", type = "qual"
      ) +
      scale_color_manual(values = c("black"), name = "averaging ensemble") +
      scale_y_reverse() +
      theme(axis.text.x = element_text(angle = 90))

    print(acc_plot / nll_plot / ece_plot + plot_layout(guides = "collect") +
      plot_annotation(title = paste(
        "Ensemble metrics",
        paste(
          c("Error inconsistency", cur_ens_cal$err_incons[[1]]),
          collapse = " "
        ),
        paste(
          c("Average pairwise accuracy variance", cur_ens_cal$mean_pwa_var[[1]]),
          collapse = " "
        ),
        sep = "\n"
      )))
  }
}
```

```{r, fig.height=18, fig.width=9}
xax <- c(
  "err_incons", "mean_pwa_var"
)
yax <- c("acc_imp_max", "acc_imp_avg")

for (xa in xax)
{
  for (ya in yax)
  {
    cur_plot <- ggplot() +
      geom_point(
        data = ens_cal_plt_df,
        mapping = aes_string(x = xa, y = ya, color = shQuote("cal ensemble")),
        alpha = 0.5
      ) +
      geom_point(
        data = ens_pwc_plt_df,
        mapping = aes_string(x = xa, y = ya, color = "coupling_method"),
        alpha = 0.5
      ) +
      facet_grid(rows = vars(combining_method)) +
      ggtitle(sprintf(
        "Accuracy improvement of ensemble over
      the %s of networks vs %s.",
        if (ya == "acc_imp_max") "best" else "average", xa
      )) +
      coord_cartesian(ylim=c(0, 0.1)) +
      theme(strip.text.y = element_text(size = 8, angle = 0))

    print(cur_plot)
  }
}

for (sss in unique(ens_cal_plt_df$combination_size))
{
  cur_ens_cal_plt_df <- ens_cal_plt_df %>% filter(combination_size == sss)
  cur_ens_pwc_plt_df <- ens_pwc_plt_df %>% filter(combination_size == sss)
  for (xa in xax)
  {
    for (ya in yax)
    {
      cur_plot <- ggplot() +
        geom_point(
          data = cur_ens_cal_plt_df,
          mapping = aes_string(x = xa, y = ya, color = shQuote("cal ensemble")),
          alpha = 0.5
        ) +
        geom_point(
          data = cur_ens_pwc_plt_df,
          mapping = aes_string(x = xa, y = ya, color = "coupling_method"),
          alpha = 0.5
        ) +
        facet_grid(rows = vars(combining_method)) +
        ggtitle(sprintf(
          "Accuracy improvement of ensemble over
        the %s of networks vs %s.
        Ensemble size %s",
          if (ya == "acc_imp_max") "best" else "average", xa, sss
        )) +
        coord_cartesian(ylim=c(0, 0.1)) +
        theme(strip.text.y = element_text(size = 8, angle = 0))

      print(cur_plot)
    }
  }
}
```
```{r}
avg_imp_table <- rbind(
  ens_pwc_plt_df %>%
    mutate(method = paste(combining_method, coupling_method, sep=" ")) %>%
    group_by(method) %>%
    summarise(imp_o_avg = mean(acc_imp_avg), imp_o_max = mean(acc_imp_max)),
  ens_cal_plt_df %>%
    mutate(method = paste0("average of ", calibrating_method)) %>%
    group_by(method) %>%
    summarise(imp_o_avg = mean(acc_imp_avg), imp_o_max = mean(acc_imp_max))
)
```
```{r, fig.width=9, fig.height=20}
imp_avg_plot <- ggplot() +
  geom_boxplot(data = ens_pwc_plt_df, mapping = aes(x = coupling_method, y = acc_imp_avg)) +
  geom_boxplot(data = ens_cal_plt_df, mapping = aes(x = calibrating_method, y = acc_imp_avg)) +
  facet_grid(rows = vars(combining_method)) +
  ggtitle("Accuracy improvement over the average of networks") +
  theme(strip.text.y = element_text(size = 8, angle = 0))


print(imp_avg_plot)
print(imp_avg_plot + coord_cartesian(ylim=c(0, 0.1)))
```

```{r, results='asis'}
print(xtable(avg_imp_table %>% arrange(desc(imp_o_avg)), digits=c(0, 0, 4, 4)), tabular.environment="longtable", floating=FALSE)
```

```{r, fig.width=9, fig.height=20}
imp_max_plot <- ggplot() +
  geom_boxplot(data = ens_pwc_plt_df, mapping = aes(x = coupling_method, y = acc_imp_max)) +
  geom_boxplot(data = ens_cal_plt_df, mapping = aes(x = calibrating_method, y = acc_imp_max)) +
  facet_grid(rows = vars(combining_method)) +
  ggtitle("Accuracy improvement over the best network") +
  theme(strip.text.y = element_text(size = 8, angle = 0))


print(imp_max_plot)
print(imp_max_plot + coord_cartesian(ylim=c(0, 0.07)))
```

```{r, results='asis'}
print(xtable(avg_imp_table %>% arrange(desc(imp_o_max)), digits=c(0, 0, 4, 4)), tabular.environment="longtable", floating=FALSE)
```

```{r}
avg_imp_table_cs <- rbind(
  ens_pwc_plt_df %>%
    mutate(method = paste(combining_method, coupling_method, sep=" ")) %>%
    group_by(method, combination_size) %>%
    summarise(imp_o_avg = mean(acc_imp_avg), imp_o_max = mean(acc_imp_max)),
  ens_cal_plt_df %>%
    mutate(method = paste0("average of ", calibrating_method)) %>%
    group_by(method, combination_size) %>%
    summarise(imp_o_avg = mean(acc_imp_avg), imp_o_max = mean(acc_imp_max))
)
```

```{r, fig.width=9, fig.height=22}
for (sss in unique(ens_cal_plt_df$combination_size))
{
  imp_avg_plot <- ggplot() +
    geom_boxplot(data = ens_pwc_plt_df %>% filter(combination_size == sss), mapping = aes(x = coupling_method, y = acc_imp_avg)) +
    geom_boxplot(data = ens_cal_plt_df %>% filter(combination_size == sss), mapping = aes(x = calibrating_method, y = acc_imp_avg)) +
    facet_grid(rows = vars(combining_method)) +
    ggtitle(sprintf("Accuracy improvement over the average of networks, ensemble size %s", sss)) +
    theme(strip.text.y = element_text(size = 8, angle = 0))


  print(imp_avg_plot)
  print(imp_avg_plot + coord_cartesian(ylim=c(0, 0.1)))

  imp_max_plot <- ggplot() +
    geom_boxplot(data = ens_pwc_plt_df %>% filter(combination_size == sss), mapping = aes(x = coupling_method, y = acc_imp_max)) +
    geom_boxplot(data = ens_cal_plt_df %>% filter(combination_size == sss), mapping = aes(x = calibrating_method, y = acc_imp_max)) +
    facet_grid(rows = vars(combining_method)) +
    ggtitle(sprintf("Accuracy improvement over the best of networks, ensemble size %s", sss)) +
    theme(strip.text.y = element_text(size = 8, angle = 0))


  print(imp_max_plot)
  print(imp_max_plot + coord_cartesian(ylim=c(0, 0.07)))

}
```

```{r, results='asis'}
for (sss in unique(ens_cal_plt_df$combination_size))
{
  print(xtable(avg_imp_table_cs %>% filter(combination_size == sss) %>% arrange(desc(imp_o_avg)), digits=c(0, 0, 0, 4, 4)), tabular.environment="longtable", floating=FALSE)
  print(xtable(avg_imp_table_cs %>% filter(combination_size == sss) %>% arrange(desc(imp_o_max)), digits=c(0, 0, 0, 4, 4)), tabular.environment="longtable", floating=FALSE)
}
```



